"""PDF export service for itinerary download."""
from __future__ import annotations

from datetime import datetime
from typing import Any

from jinja2 import Template

ITINERARY_HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; color: #1a1a1a; }
  h1 { color: #1e3a5f; border-bottom: 3px solid #1e3a5f; padding-bottom: 10px; }
  h2 { color: #2d6a4f; margin-top: 30px; }
  .day { margin-bottom: 30px; page-break-inside: avoid; }
  .day-header { background: #f0f7ff; padding: 10px 15px; border-radius: 8px; margin-bottom: 10px; }
  .item { padding: 8px 15px; border-left: 3px solid #ccc; margin: 5px 0; }
  .item.flight { border-color: #e63946; }
  .item.hotel { border-color: #457b9d; }
  .item.activity { border-color: #2a9d8f; }
  .item.food { border-color: #e9c46a; }
  .time { font-weight: bold; color: #555; }
  .cost { float: right; color: #888; }
  .reasoning { font-style: italic; color: #666; font-size: 0.9em; }
  .weather { background: #fff3cd; padding: 5px 10px; border-radius: 4px; font-size: 0.9em; }
  .summary { background: #d4edda; padding: 15px; border-radius: 8px; margin: 20px 0; }
  .checklist { columns: 2; }
  .checklist li { margin-bottom: 5px; }
  footer { margin-top: 40px; text-align: center; color: #888; font-size: 0.8em; }
</style>
</head>
<body>
<h1>🌍 {{ destination }} Trip Itinerary</h1>
<p><strong>Dates:</strong> {{ start_date }} — {{ end_date }} |
   <strong>Budget:</strong> {{ currency }} {{ "%.0f"|format(total_cost) }} |
   <strong>Travelers:</strong> {{ traveler_count }}</p>

{% for day in days %}
<div class="day">
  <div class="day-header">
    <h2>Day {{ day.day }} — {{ day.date }}{% if day.title %}: {{ day.title }}{% endif %}</h2>
    {% if day.weather %}
    <div class="weather">{{ day.weather.condition | capitalize }} · {{ day.weather.high_temp_c }}°C / {{ day.weather.low_temp_c }}°C · {{ day.weather.recommendation }}</div>
    {% endif %}
  </div>
  {% for item in day.items %}
  <div class="item {{ item.category }}">
    <span class="time">{% if item.start_time %}{{ item.start_time }}{% endif %}</span>
    {{ item.title }}
    {% if item.cost %}<span class="cost">{{ currency }} {{ "%.0f"|format(item.cost) }}</span>{% endif %}
    {% if item.description %}<br><small>{{ item.description }}</small>{% endif %}
    {% if item.reasoning %}<br><span class="reasoning">Why: {{ item.reasoning }}</span>{% endif %}
  </div>
  {% endfor %}
  <p><em>Daily spend: {{ currency }} {{ "%.0f"|format(day.daily_spend) }}</em></p>
</div>
{% endfor %}

<div class="summary">
  <h2>Trip Summary</h2>
  <p><strong>Total Estimated:</strong> {{ currency }} {{ "%.0f"|format(total_cost) }}</p>
  <p><strong>Flexibility Score:</strong> {{ "%.0f"|format(flexibility_score * 100) }}%</p>
</div>

{% if packing_list %}
<h2>🎒 Packing List</h2>
<ul class="checklist">
{% for item in packing_list %}
  <li>☐ {{ item }}</li>
{% endfor %}
</ul>
{% endif %}

{% if checklist %}
<h2>✅ Pre-Trip Checklist</h2>
<ul class="checklist">
{% for item in checklist %}
  <li>☐ {{ item }}</li>
{% endfor %}
</ul>
{% endif %}

<footer>Generated by HolidayPilot · {{ generated_at }}</footer>
</body>
</html>
"""


def render_itinerary_html(itinerary: dict, trip: dict) -> str:
    template = Template(ITINERARY_HTML_TEMPLATE)
    return template.render(
        destination=trip.get("destination", "Your Trip"),
        start_date=trip.get("start_date", ""),
        end_date=trip.get("end_date", ""),
        currency=itinerary.get("currency", "USD"),
        total_cost=itinerary.get("total_cost", 0),
        flexibility_score=itinerary.get("flexibility_score", 0),
        traveler_count=len(trip.get("travelers", [])) or 1,
        days=itinerary.get("days", []),
        packing_list=itinerary.get("packing_list", []),
        checklist=itinerary.get("checklist", []),
        generated_at=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
    )


async def generate_pdf(itinerary: dict, trip: dict) -> bytes:
    """Generate PDF from itinerary. Falls back to HTML if WeasyPrint unavailable."""
    html = render_itinerary_html(itinerary, trip)
    try:
        from weasyprint import HTML
        return HTML(string=html).write_pdf()
    except ImportError:
        return html.encode("utf-8")
